### PR TITLE
add option to order results and make sure to pull from top

### LINKED ISSUE #146: integrate orderBy
It'd be useful to have an orderby paramter in featurelayerprovider

### PR DESCRIPTION
**Pull request by jgravois**
resolves #146.

this change exposes the orderBy method of [`L.esri.query`](http://esri.github.io/esri-leaflet/api-reference/tasks/query.html#methods) to the provider as well.

``` js
var flProvider = L.esri.Geocoding.featureLayerProvider({
  label: 'States',
  url: 'http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3',
  searchFields: ['STATE_NAME']
})

flProvider.orderBy('POP2007', 'ASC') // alaska has the smallest population, texas the largest (just the way they like it)
flProvider.suggestions('as', null, function (error, results) {
  console.log(results);
});
```

previously we weren't plucking results from the top of the array returned by the service.  that needed fixed too.

@nickpeihl do you have time to give this a quick sanity check?  if so i'd be ready to merge and tag a new release.

### CODE REVIEW

**Comment by nickpeihl** [comment]
Oh dear. Somehow I missed this. Sorry about that.

**Comment by jgravois** [comment]
no worries!
the code is in `master` now, but its *never* too late for code review &#169;

**Comment by nickpeihl** [comment]
Hey this is keen! Nice work!
http://jsbin.com/xeyewasizi/edit?html,output

My name is @nickpeihl and I approve this PR. :+1:

**Comment by jgravois** [comment]
@nickpeihl much appreciated!

**Pull request merged**
