### PR TITLE
feat: TypeScript types file [#319]

### PR DESCRIPTION
**Pull request by nooras**
Description:
TypeScript types file 

Fix: #319 

@gavinr-maps 
Kindle please review the PR.

### CODE REVIEW

**Comment by gavinr-maps** [comment]
@nooras can you please add replication steps to tell us how you tested to ensure these are working properly? Thanks!

**Comment by gavinr-maps** [comment]
Can you also please add the `index.d.ts` file to the `files` array in the `package.json` per here:

- https://github.com/Esri/esri-leaflet-vector/issues/154#issuecomment-1485860049
- https://github.com/Esri/esri-leaflet-vector/pull/167

Also I think you need to include the providers, from here: https://developers.arcgis.com/esri-leaflet/api-reference/controls/geosearch/#providers

**Review by gavinr-maps — CHANGES_REQUESTED** [review]
Thanks for the PR!

Can you also please add the `index.d.ts` file to the `files` array in the `package.json` per here:

- https://github.com/Esri/esri-leaflet-vector/issues/154#issuecomment-1485860049
- https://github.com/Esri/esri-leaflet-vector/pull/167

Also I think you need to include the providers, from here: https://developers.arcgis.com/esri-leaflet/api-reference/controls/geosearch/#providers

**Comment by nooras** [comment]
hey @gavinr-maps 
Can you please check the changes
`npm test`
image

**Comment by gavinr-maps** [comment]
works for me! @hhkaos can you please test?

**Review by gavinr-maps — APPROVED** [review]

**Review by hhkaos — APPROVED** [review]
Everything looks good to me too! 👏 😄 
Screenshot 2024-10-24 at 14 33 35

**Pull request merged**
