### PR TITLE
Case Sensitive option on Feature Layer

### PR DESCRIPTION
**Pull request by rntdrts**
Don't know if this is the right approach, hope someone can tell me..

### CODE REVIEW

**Comment by jgravois** [comment]
thanks @rntdrts!  i'll take a closer look at this sometime soon.

**Comment by patrickarlt** [comment]
@rntdrts does this actually work? Most evidence I can find and my own testing indicates that the SQL `LIKE` keyword isn't case sensitive so searching feature  `LIKE '%paris%'` and `like '%PARIS%'` is actually the same thing, for example:

https://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/GIS_Day_Final/FeatureServer/0/query?where=Name+LIKE+%27%25GIS%25%27&returnCountOnly=true&f=json

vs

https://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/GIS_Day_Final/FeatureServer/0/query?where=Name+LIKE+%27%25gis%25%27&returnCountOnly=true&f=json

both return 617 features.

2nd it also looks like you are applying `upper()` to the field name not the input value https://github.com/Esri/esri-leaflet-geocoder/pull/83/files#diff-ea6dcc5c56253a2f4fb3d45be9fc7385R92 the query statement needs to be formatted like `column LIKE '%input text%'` with this change the query would be formatted like `upper(column) LIKE '%input text%'` which would uppercase the column name.

**Comment by rntdrts** [comment]
@patrickarlt This works. I'm just not sure if this should be done on the provider or if is something not setted on the server side. On the company that i work i did implement this has a custom provider, i will let here some examples so you can also see the difference:

http://arcgisserver.ubiprism.pt/arcgis/rest/services/Toponimia/FeatureServer/0/query?where=Nome+LIKE+%27%25Rua%25%27&returnCountOnly=true&f=json

```{"count":4541}````

now with lower and upper:

http://arcgisserver.ubiprism.pt/arcgis/rest/services/Toponimia/FeatureServer/0/query?where=Nome+LIKE+%27%25rua%25%27&returnCountOnly=true&f=json
```{"count":0}```
http://arcgisserver.ubiprism.pt/arcgis/rest/services/Toponimia/FeatureServer/0/query?where=Nome+LIKE+%27%25RUA%25%27&returnCountOnly=true&f=json
```{"count":0}```

Now the request that is implemented above:
http://arcgisserver.ubiprism.pt/arcgis/rest/services/Toponimia/FeatureServer/0/query?where=upper(nome)+LIKE+%27%25RUA%25%27&returnCountOnly=true&f=json
```{"count":4541}````

Thanks for your time, both of you. I really appreciated :)

**Comment by rntdrts** [comment]
@patrickarlt Let me ask you something, what is the database you use on your services?

**Comment by jgravois** [comment]
thanks for the additional clarification and example service @rntdrts.

we've tested against a variety, but i'd say the bulk are probably SQL Server.
i've never seen the behavior you're reporting before but it seems like something we can/should fix in this plugin.

that being said, i'd call your tweak `caseInsensitive` or `caseSensitive = false` because you're making it so that a match is returned when the casing **doesn't** match.

**Comment by jgravois** [comment]
> it also looks like you are applying `upper()` to the field name not the input value

@patrickarlt thats legitimate sql syntax to modify the value of a particular attribute before comparing to the search string

**Comment by jgravois** [comment]
just got confirmation that upper() is an ANSI standard SQL function that all major RDBMS should support.  thinking about all this more, i'd vote that we don't expose an option in the plugin constructor, we should just incorporate @rntdrts's new logic all the time.

as long as we're getting esoteric, its also mandatory to encase fieldnames in double quotes within the upper() function if a fieldname contains a space, so we'd be more bulletproof if we did that as well.

> upper("field name") LIKE ...

@rntdrts would you be game for making the changes i mentioned and then rebasing against master to resolve conflicts?

**Comment by patrickarlt** [comment]
@jgravois @rntdrts Ok I'm convinced that this is the right approach. It looks like @rntdrts's database is case sensitive. @jgravois and I also got this from the database team

> By default, we often see SQL Server set to be case insensitive, whereas Oracle and PostgreSQL seem to default to being case sensitive.

So this makes sense since I think ArcGIS Online is SQL Server. However this only solves the use case where your trying to make a query match uppercased data. In this case making `rua` match `Rua`. This doesn't solve the case in the opposite direction, trying to make `Paris` match `paris`.

I chatted with @JerrySievert my ever-reliable SQL resource who recommended the following

```sql
upper(nome) LIKE upper('%rua%')
```

This appears achieve the desired effect producing results for `Rua`, `RUA`, and `rua`. It's worth noting that `lower(column) LIKE lower('%input%') ` also appears to work. It is also worth noting that this basically force case **insensitivity** by forcing everything to a particular case.

So here is my recommendation. In order to create the best possible UX we should ALWAYS format all queries like `upper(column) LIKE upper('%input%')` and not have a `caseSensitive `. I think what @rntdrts wants is for a search for `rua` to produce results. This isn't about providing a new option to make it work specifcally with case sensitive databases. It is about making it work with every database. Formatting everything like `upper(column) LIKE upper('%input%')` just works and produces the desired results against both Online and @rntdrts's server.

**Comment by rntdrts** [comment]
@jgravois of course i will do it. however i was thinking almost the same has @patrickarlt this should be a pattern and not an option, i also agree that we should keep a standard on the solution, if we can do it in both fields with the ```upper()``` so be it.

If we both agree i will implement this on both fields, the column and the input. Thanks for the time, i really appreciate.

**Comment by jgravois** [comment]
tested this manually and it worked great.  thanks for the catch and the fix @rntdrts!

**Pull request merged**
