### PR TITLE
Add "searchMode" option for Feature Layer Provider

### PR DESCRIPTION
**Pull request by pmacMaps**
Possible values for "searchMode":
-  "contain" = wildcard
-  "startWith" = starting text and then wildcard after
-  "endWith" = wildcard then text
-  "strict" = entered text must match exactly

### CODE REVIEW

**Comment by gavinr** [comment]
Thanks for all your work on this @pmacMaps. Really appreciate it. I tested out the functionality and it seems to work as expected. Added functionality like this calls for unit tests, so we should tack on some unit tests to this PR. I understand that you've done a lot of work on this already, so if you'd like to add those - we would appreciate it but if not, I'll try to find some time to add them.

**Comment by pmacMaps** [comment]
I can take a stab at the unit tests. I've never made any before, so any links or guidance is appreciated.

I know we'll also need to update the API reference.

**Comment by gavinr** [comment]
@pmacMaps I believe the additional unit tests will go in https://github.com/Esri/esri-leaflet-geocoder/blob/master/spec/Providers/FeatureLayerSpec.js - right now it has a `beforeEach` which runs on each test, I think we'll have to change that so that you have a separate "section" of tests that will create a privder that the new `searchMode` parameter and then runs a few tests to make sure the url that is used is correct. 

we are using [karma](https://karma-runner.github.io/latest/index.html), but you'll mostly want to focus on the [mocha](https://mochajs.org/#table-of-contents) documentation.

**Comment by pmacMaps** [comment]
The unit tests may get written faster if someone with experience tackles the issue.  I can definitely update the API reference once this functionality ships.

**Comment by jgravois** [comment]
> The unit tests may get written faster if someone with experience tackles the issue.

no pressure, but i can say from personal experience that i was initially extremely intimidated by the idea of writing unit tests and that the intimidation gave way to immense gratification when i finally stuck my toe in the water.

if you're interested, you can learn heaps by making tiny changes to existing tests one at a time to get practical experience breaking and fixing them. to this day, when i write new tests i still usually rely heavily on existing tests in the suite and just follow the patterns when writing new tests without worrying about understanding exactly how they work.

for you the existing test below would be a great one to copy/paste and alter slightly:
https://github.com/Esri/esri-leaflet-geocoder/blob/223c4e964b500f535cd20dad07d6ff5e31077e8a/spec/Controls/GeosearchSpec.js#L112-L131

you'd just need to ensure your own test instantiated a provider using the new option you added and make sure it tests for the corresponding `text={value}`.

**Pull request merged**
