### PR TITLE
bug-fix - adding 'input' event to handler managing 'keyup' event to e…

### PR DESCRIPTION
**Pull request by UsgsMonkey**
bug-fix - adding 'input' event to handler managing 'keyup' event to ensure copy/paste submission to the control is read properly

### CODE REVIEW

**Comment by jgravois** [comment]
putting the test failures on hold briefly, can you describe in a little more detail what problem this change resolves?

in Chrome 65, when i copy/paste the string `"LAX"` into [this sample](http://esri.github.io/esri-leaflet/examples/geocoding-control.html) and click <kbd>Enter</kbd>, three results are displayed.

copy_paste

**Comment by UsgsMonkey** [comment]
hmmm.... that's definitely not the behavior we were observing.  After pasting and hitting a carriage return, the control wasn't responding.  Perhaps Chrome 65 had an update?  It's hard for me to go backwards and test on Chrome 64 because we're on government systems (I know the update happened for us from 64 to 65 fairly recently).

**Comment by UsgsMonkey** [comment]
One thing to note - we are loading a number of searches into this control... including searches against some of our own hosted map services.  Perhaps it behaves differently vs. these as opposed to searches vs. ArcGIS Online?

**Comment by jgravois** [comment]
i'm confused. are you still able to reproduce the error or not?

**Comment by UsgsMonkey** [comment]
Good question... let me check...

**Comment by UsgsMonkey** [comment]
Ok, I removed the update and it's definitely working vs. Chrome 65.  I know this wasn't my imagination though as this issue had been replicated many times across multiple machines...  All I can suggest is perhaps Chrome made some kind of change that solved this problem for us *shrug*.  It's a good problem to have I guess - but I'd love to know what changed.

**Comment by jgravois** [comment]
> I'd love to know what changed.

me too 😺. for the time being lets just call it a (resolved) Chrome bug that we no longer need to workaround. if you're ever able to reproduce again in the future, i'm happy to revisit.

**Pull request closed without merging**
