### PR TITLE
Build update

### PR DESCRIPTION
**Pull request by JeffJacobson**
Resolves build error described in #305

### CODE REVIEW

**Comment by patrickarlt** [comment]
@JeffJacobson this looks good but `node-sass` is deprecated now. Would you be willing to switch this to [`sass`](https://sass-lang.com/install)? If not I'll merge this and make a note to switch later.

**Comment by JeffJacobson** [comment]
> @JeffJacobson this looks good but `node-sass` is deprecated now. Would you be willing to switch this to [`sass`](https://sass-lang.com/install)? If not I'll merge this and make a note to switch later.

I'll take a little time to see if I can implement the change to `sass`. If I can get it working I'll push to this pull request's branch.  

If you don't hear back from me in a day or two, then I would suggest you merge and "make a note to switch later". The build issue I addressed is a hindrance to any other devs that want to contribute to the project, so I think it's pretty important.

**Comment by JeffJacobson** [comment]
Should I also remove the bower and/or travis-ci configs? 

I think bower would be safe to remove, but I didn't know if you're still using travis-ci.com rather than the discontinued travis-ci.org.

I won't remove either unless you tell me otherwise.

**Comment by patrickarlt** [comment]
I would just leave bower and travis ci alone. I cant remember off the top of  my head and it outside the scope of this issue. Thanks for contributing!

**Comment by JeffJacobson** [comment]
OK, I think it's all done now.

**Review by gavinr — APPROVED** [review]
Thanks!

**Comment by gavinr** [comment]
This was released in [v3.1.4](https://github.com/Esri/esri-leaflet-geocoder/releases/tag/v3.1.4).

**Pull request merged**
